FROM amacneil/dbmate

ENV DBMATE_MIGRATIONS_DIR=/db/migrations
ENV DBMATE_SCHEMA_FILE=/db/schema.sql

COPY internal/db/migrations /db/migrations
COPY internal/generated/db/schema.sql /db/schema.sql

CMD ["dbmate", "--no-dump", "--no-rollback", "--no-seed", "--no-setup", "up"]