version: '3.8'
services:
  snapfluencer-bot:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    restart: always
    environment:
      - PORT=3000
      - NODE_ENV=production
      - REDIS_URL=redis://snapfluencer-cache:6379
  snapfluencer-cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1
    volumes: 
      - snapfluencer-cache:/data
volumes:
  snapfluencer-cache:
    driver: local