version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snapfluencer
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
    driver: local